name: "Mongoid Release Candidate"
run-name: "Mongoid Release Candidate for ${{ github.ref }}"

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: Whether this is a dry run or not
        required: true
        default: true
        type: boolean

jobs:
  candidate:
    name: "Mongoid Release Candidate"
    runs-on: 'ubuntu-latest'

    permissions:
      # required for all workflows
      security-events: write

      # required to fetch internal or private CodeQL packs
      packages: read

      # only required for workflows in private repositories
      actions: read
      contents: write

      # required by the mongodb-labs/drivers-github-tools/setup@v2 step
      # also required by `rubygems/release-gem`
      id-token: write

    steps:
      - name: "Run the candidate action"
        uses: jamis/drivers-github-tools/ruby/candidate@ruby-3643-new-release-process
        with:
          app_id: ${{ vars.APP_ID }}
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          dry_run: ${{ inputs.dry_run }}
